# Generated by Django 5.1.6 on 2025-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='max_lectures_per_week',
            field=models.IntegerField(default=18),
        ),
    ]
